# Generated by Django 5.2.8 on 2025-11-14 00:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tier_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('tier_config', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('tier_level', models.CharField(max_length=200)),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tier_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TierList.tier_list')),
            ],
        ),
    ]
