# Generated by Django 5.2.8 on 2025-11-14 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TierList', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tier_list',
            new_name='Ranking',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='tier_list',
            new_name='Ranking',
        ),
    ]
