# Generated by Django 5.1.12 on 2025-11-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TierList', '0002_rename_tier_list_ranking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='type',
            field=models.CharField(default='template', max_length=200),
        ),
    ]
