# Generated by Django 5.1.12 on 2025-11-19 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TierList', '0003_ranking_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thumbnail_images/')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TierList.ranking')),
            ],
        ),
    ]
