# Generated by Django 5.1.12 on 2025-11-20 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TierList', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ranking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='TierList.ranking'),
        ),
    ]
